"""Build the ad-blocking lists from the ad-recon dataset.

Reads the raw ad recon (ad/tracker domains, cosmetic selectors, HLTV ad slots,
false-positive audit), applies the audit's exclusions, and emits:
  data/ad_domains.json   -> host blocklist for the DNR "ads" ruleset
  data/ad_selectors.js   -> globalThis.BETBLOCK_ADS (generic cosmetic selectors)
  data/ad_recon_raw.json -> provenance

Usage:
    python tools/build_ad_lists.py [path-to-adblock-recon.json]
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
DATA = BASE / "data"

# Hosts the audit flagged as dual-use (login/SDK/CDN/redirect) or malformed.
EXCLUDE_DOMAINS = {
    "t.co",                       # X link resolver — breaks real links
    "app.link",                   # Branch deep links — breaks navigation
    "connect.facebook.net",       # FB JS SDK / "Login with Facebook"
    "sc-static.net",              # Snap Kit SDK assets
    "t.teads.tv",                 # Teads in-article video runtime
    "servedbyadbutler.com",       # was malformed (leading space) in recon
    "prebid.org",                 # docs site, not an ad endpoint
    "ads.prebid.org",             # not a real ad endpoint
    "analytics.google.com",       # GA reporting dashboard, not collection
    # From the HLTV ad scan — keep these UNblocked:
    "googletagmanager.com",       # can gate real content / SPA rendering
    "www.googletagmanager.com",
    "consent.cookiebot.com",      # consent flow, not an ad
}

# Extra ad-tech hosts found in the HLTV ad stack worth blocking network-wide.
ADD_HLTV_ADTECH = [
    "htlbid.com",
    "securepubads.g.doubleclick.net",
    "pj.l.liftdsp.com",
    "ps.l.liftdsp.com",
    "pool.admedo.com",
    "r.uuidksinc.net",
]

# Cosmetic selectors the audit rejected as too broad / false-positive-prone.
EXCLUDE_SELECTORS = {
    '[id^="dfp_"]',
    ".advert",
    '[aria-label="Ad" i]',
    ".ad-container",
    ".ad-wrapper",
}


def norm_host(d: str) -> str:
    d = d.strip().lower()
    for pre in ("http://", "https://"):
        if d.startswith(pre):
            d = d[len(pre):]
    return d.strip().strip("/")


def main() -> int:
    raw_path = Path(sys.argv[1]) if len(sys.argv) > 1 else (DATA / "ad_recon_raw.json")
    blob = json.loads(raw_path.read_text(encoding="utf-8"))
    result = blob.get("result", blob)

    DATA.mkdir(parents=True, exist_ok=True)
    prov = DATA / "ad_recon_raw.json"
    if raw_path.resolve() != prov.resolve():
        prov.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")

    # --- domains -----------------------------------------------------------
    raw = list(result["adDomains"]["domains"])
    raw += list(result["audit"].get("extraSafeDomains", []))
    raw += ADD_HLTV_ADTECH

    domains = set()
    for d in raw:
        h = norm_host(d)
        if not h or "/" in h:          # drop URL-path entries (e.g. yandex.ru/metrika)
            continue
        if h in EXCLUDE_DOMAINS:
            continue
        domains.add(h)
    domains = sorted(domains)

    (DATA / "ad_domains.json").write_text(
        json.dumps({"_meta": {"count": len(domains),
                              "source": "ad recon + false-positive audit"},
                    "domains": domains}, indent=2),
        encoding="utf-8",
    )

    # --- cosmetic selectors ------------------------------------------------
    cosmetic = []
    seen = set()
    for s in result["cosmetic"]["selectors"]:
        sel = s["sel"].strip()
        if sel and sel not in EXCLUDE_SELECTORS and sel not in seen:
            seen.add(sel)
            cosmetic.append(sel)

    js = (
        "/* GENERATED by tools/build_ad_lists.py — do not edit by hand.\n"
        " * High-confidence, audited cosmetic ad selectors applied on all sites\n"
        " * when ad-blocking is on. Naive [class*=\"ad\"] matching is excluded. */\n"
        "globalThis.BETBLOCK_ADS = {\n"
        "  cosmetic: " + json.dumps(cosmetic, indent=2) + ",\n"
        "};\n"
    )
    (DATA / "ad_selectors.js").write_text(js, encoding="utf-8")

    print(f"wrote data/ad_domains.json ({len(domains)} hosts) + "
          f"data/ad_selectors.js ({len(cosmetic)} cosmetic selectors)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
